### ISSUE TITLE
Removing account triggers error and keeps account settings page open

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#2025]
```log
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      $AccountSettingsRouteExtension._fromState (package:neon_framework/src/router.g.dart:253:53)
#1      GoRouteData.$route.factoryImpl (package:go_router/src/route_data.dart:102:53)
#2      GoRouteData.$route.onExit (package:go_router/src/route_data.dart:115:9)
#3      GoRouterDelegate._callOnExitStartsAt (package:go_router/src/delegate.dart:285:54)
#4      GoRouterDelegate.setNewRoutePath (package:go_router/src/delegate.dart:232:16)
#5      _RouterState._processParsedRouteInformation.<anonymous closure> (package:flutter/src/widgets/router.dart:758:34)
#6      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:43:39)
#7      _RouterState._processRouteInformation (package:flutter/src/widgets/router.dart:750:8)
#8      _RouterState._handleRouteInformationProviderNotification (package:flutter/src/widgets/router.dart:767:5)
#9      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:433:24)
#10     GoRouteInformationProvider.notifyListeners (package:go_router/src/information_provider.dart:134:11)
#11     GoRouteInformationProvider._setValue (package:go_router/src/information_provider.dart:144:7)
#12     GoRouteInformationProvider.go (package:go_router/src/information_provider.dart:166:5)
#13     GoRouter.go (package:go_router/src/router.dart:340:30)
#14     GoRouterHelper.go (package:go_router/src/misc/extensions.dart:25:25)
#15     $HomeRouteExtension.go (package:neon_framework/src/router.g.dart:93:44)
#16     AccountSettingsPage.build.<anonymous closure> (package:neon_framework/src/pages/account_settings.dart:76:37)
<asynchronous suspension>
```

**Comment by provokateurin** [comment]
Not reproducible anymore (neither with multiple or single account). Likely some weird race condition, but I can't tell if got fixed randomly or not.
