### ISSUE TITLE
Message polling runs into TimeoutException

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#2498]
```
[TalkRoomBloc] Polling messages
[TalkRoomBloc] Error while waiting for new chat messages
               ClientException: TimeoutException after 0:00:30.000000: Future not completed, uri=https://cloud.nextcloud.com/ocs/v2.php/apps/sp...
               #0      NeonHttpClient.send (package:neon_http_client/src/neon_http_client.dart:84:7)
               <asynchronous suspension>
               #1      $ChatClient.receiveMessages (package:nextcloud/src/api/spreed/spreed.openapi.dart:3841:31)
               <asynchronous suspension>
               #2      new _TalkRoomBloc.<anonymous closure> (package:talk_app/src/blocs/room.dart:137:28)
               <asynchronous suspension>
```

Ideally we disable timeouts for this request, as this request is expected to take long. In reality it's not a problem as the server also cancels the request after 30s, but it's still better to let the server control this.
@Leptopoda do we have a way to disable the timeout for this request?

**Comment by Leptopoda** [comment]
I don't think so.
AFAIK we can only set the timeout for the entire http client (at least on dart:io). I have no idea, whether the web client even has a timeout)
